apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: strimzi
  name: grafana-config
  namespace: kevin
data:
  datasources.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-service:8080
      isDefault: true
      editable: false

  # dashboard provider
  provider.yaml: |-
    apiVersion: 1
    providers:
    - name: 'aniskhan001'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      updateIntervalSeconds: 10
      options:
        path: /var/lib/grafana/dashboards
