{
 "title": "CPU Usage Details",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Source", "query": "prometheus" },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "query_result(container_cpu_usage_seconds_total)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster CPU Usage ($interval avg)",
   "type": "singlestat",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Namespace: [ $kubernetes_namespace ]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",name=~\"^k8s_.*\",namespace=\"$kubernetes_namespace\"}[$interval])) by (container_name)",
     "legendFormat": "{{ container_name }}"
    }
   ]
  }
 ]
}
{
 "title": "Strimzi Kafka",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "query_result(kafka_server_replicamanager_leadercount)"
   },
   {
    "name": "strimzi_cluster_name",
    "label": "Cluster Name",
    "query": "query_result(kafka_server_replicamanager_leadercount{kubernetes_namespace=\"$kubernetes_namespace\"})"
   },
   {
    "name": "kafka_broker",
    "label": "Broker",
    "query": "query_result(kafka_server_replicamanager_leadercount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
   },
   {
    "name": "kafka_topic",
    "label": "Topic",
    "query": "query_result(kafka_cluster_partition_replicascount{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"})"
   },
   {
    "name": "kafka_partition",
    "label": "Partition",
    "query": "query_result(kafka_log_log_size{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\",topic=~\"$kafka_topic\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "singlestat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_controller_controllerstats_uncleanleaderelections_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Online Replicas",
   "type": "singlestat",
   "description": "Replicas that are online",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Kafka Broker Pods Memory Usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$kubernetes_namespace\",pod_name=~\"$strimzi_cluster_name-$kafka_broker\",container_name=\"kafka\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Aggregated Kafka Broker Pods CPU Usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{namespace=\"$kubernetes_namespace\",pod_name=~\"$strimzi_cluster_name-$kafka_broker\",container_name=\"kafka\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "graph",
   "description": "Kafka Broker Pods Disk Usage",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=\"$kubernetes_namespace\",persistentvolumeclaim=~\"data(-[0-9]+)?-$strimzi_cluster_name-kafka-[0-9]+\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_memory_bytes_used{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_name=~\"$strimzi_cluster_name-$kafka_broker\"}[5m])) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_name=~\"$strimzi_cluster_name-$kafka_broker\"}[5m])) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_name=~\"$strimzi_cluster_name-$kafka_broker\"}[5m])) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Total Incoming Byte Rate",
   "type": "singlestat",
   "description": "Total Incoming Byte Rate",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Outgoing Byte Rate",
   "type": "singlestat",
   "description": "Total Outgoing Byte Rate",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))"
    }
   ]
  },
  {
   "title": "Incoming Messages Rate",
   "type": "singlestat",
   "description": "Incoming Messages Rate",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate",
   "type": "singlestat",
   "description": "Total Produce Request Rate",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))"
    }
   ]
  },
  {
   "title": "Byte Rate",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))",
     "legendFormat": "Total Incoming Byte Rate"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))",
     "legendFormat": "Total Outgoing Byte Rate"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))",
     "legendFormat": "Total Incoming Messages Rate"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "graph",
   "description": "Produce Request Rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))",
     "legendFormat": "Total Produce Request Rate"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))",
     "legendFormat": "Failed Produce Request Rate"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))",
     "legendFormat": "Fetch Request Rate"
    },
    {
     "expr": "  sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",topic=~\"$kafka_topic\",topic!=\"\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}[1m]))",
     "legendFormat": "Failed Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent",
   "type": "graph",
   "description": "Network Processor Avg Idle Percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_network_socketserver_networkprocessoravgidle_percent{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}*100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "graph",
   "description": "Request Handler Avg Idle Percent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_requesthandleravgidle_percent{namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",kubernetes_pod_name=~\"$strimzi_cluster_name-$kafka_broker\"}*100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}
{
 "title": "Strimzi ZooKeeper",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "query_result(zookeeper_inmemorydatatree_nodecount)"
   },
   {
    "name": "strimzi_cluster_name",
    "label": "Cluster Name",
    "query": "query_result(zookeeper_inmemorydatatree_nodecount{kubernetes_namespace=\"$kubernetes_namespace\"})"
   },
   {
    "name": "zk_node",
    "label": "Node",
    "query": "query_result(zookeeper_inmemorydatatree_nodecount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\"})"
   }
  ]
 },
 "panels": [
  { "title": "Zookeeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quorum Size",
   "type": "singlestat",
   "description": "Quorum Size of Zookeeper ensemble",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(zookeeper_quorumsize{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",strimzi_io_kind=\"Kafka\"})"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "singlestat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",strimzi_io_kind=\"Kafka\",kubernetes_name=~\"$strimzi_cluster_name-$zk_node\"})"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",strimzi_io_kind=\"Kafka\",kubernetes_name=~\"$strimzi_cluster_name-$zk_node\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",strimzi_io_kind=\"Kafka\"})"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "singlestat",
   "description": "Number of Watchers",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(zookeeper_inmemorydatatree_watchcount{kubernetes_namespace=\"$kubernetes_namespace\",strimzi_io_cluster=\"$strimzi_cluster_name\",strimzi_io_kind=\"Kafka\",kubernetes_name=~\"$strimzi_cluster_name-$zk_node\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Kafka Broker Pods Memory Usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{namespace=\"$kubernetes_namespace\",container_name=\"zookeeper\",pod_name=~\"$strimzi_cluster_name-$zk_node\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Aggregated Kafka Broker Pods CPU Usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{namespace=\"$kubernetes_namespace\",container_name=\"zookeeper\",pod_name=~\"$strimzi_cluster_name-$zk_node\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "graph",
   "description": "Kafka Broker Pods Disk Usage",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=\"$kubernetes_namespace\",persistentvolumeclaim=~\"data(-[0-9]+)?-$strimzi_cluster_name-zookeeper-[0-9]+\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_memory_bytes_used{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_name=~\"$strimzi_cluster_name-$zk_node\"}[5m])) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_name=~\"$strimzi_cluster_name-$zk_node\"}[5m])) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_name=~\"$strimzi_cluster_name-$zk_node\"}[5m])) by (kubernetes_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Request Latency - Minimum",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_minrequestlatency{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_name=~\"$strimzi_cluster_name-$zk_node\"}",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Request Latency - Average",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_avgrequestlatency{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_name=~\"$strimzi_cluster_name-$zk_node\"}",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  },
  {
   "title": "Request Latency - Maximum",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_maxrequestlatency{kubernetes_namespace=\"$kubernetes_namespace\",kubernetes_name=~\"$strimzi_cluster_name-$zk_node\"}",
     "legendFormat": "{{kubernetes_name}}"
    }
   ]
  }
 ]
}